name: core
version: 0.0.1
publish_to: none
description: Project core module

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  get_it: ^7.6.4
  dio: ^5.4.0
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.3
  intl: ^0.18.0
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  url_launcher: ^6.2.2
  flutter_screenutil: ^5.9.0
  jwt_decoder: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - resources/icons/svg/
    - resources/icons/png/
    - resources/icons/gif/
    - resources/translations/
